### ISSUE TITLE
Edit MTU Multiple servers

### ISSUE THREAD

**Issue by pouriasharifzad** [Azumi67/6TO4-GRE-IPIP-SIT#22]
وقتی میخوام mtu روی سرور ایران برای 5تا سرور خارج رو ادیت کنم بعد از سرور 2 این ارور رو میده

───────────────────────────────────────
✨              Server 1
───────────────────────────────────────
Enter the MTU value [ Private IP ]: 1322
MTU command edited successfully
───────────────────────────────────────
✨              Server 2
───────────────────────────────────────
Enter the MTU value [ Private IP ]: 1322
MTU command edited successfully
───────────────────────────────────────
Traceback (most recent call last):
  File "/dev/fd/63", line 57092, in <module>
  File "/dev/fd/63", line 220, in main_menu
  File "/dev/fd/63", line 37882, in mtu2_menu
  File "/dev/fd/63", line 39042, in private_mnu
  File "/dev/fd/63", line 39090, in khprivate_mnu
  File "/dev/fd/63", line 39134, in mtu1_q
  File "/dev/fd/63", line 39152, in mtu1_q1
  File "/dev/fd/63", line 40413, in priv_ir3_mtu
NameError: name 'ddisplay_notification' is not defined

**Comment by Azumi67** [comment]
سلام ممنون اطلاع دادید . من دارم ده سرور‌ و ویرایش سرور‌ رو به اسکریپت اضافه میکنم . این هم نگاه میکنم.

**Comment by pouriasharifzad** [comment]
عالیه ممنون از زحماتتون

**Comment by Azumi67** [comment]
فکر کنم الان باید درست شده باشه.
